### PR TITLE
Use commit for MLT 6.12 when building Flatpak.

### PR DESCRIPTION
**Pull request by jliljebl**
Let's use this first, if we have problems we can try to downgrade to some another version and get a fix in MLT.

### CODE REVIEW

**Comment by eszlari** [comment]
I tested that version locally and it's still broken.

To test this locally:

```
git clone --recurse-submodules https://github.com/flathub/io.github.jliljebl.Flowblade.git
cd io.github.jliljebl.Flowblade
flatpak install flathub org.gnome.Platform//3.30
flatpak install flathub org.gnome.Sdk//3.30
flatpak-builder --ccache --install --force-clean buid_dir io.github.jliljebl.Flowblade.yaml
flatpak run io.github.jliljebl.Flowblade
```

**Comment by jliljebl** [comment]
Ok, after I do command:

flatpak-builder --ccache --install --force-clean build_dir io.github.jliljebl.Flowblade.yaml

I get:

Can't parse 'io.github.jliljebl.Flowblade.yaml': <data>:1:2: Parse error: unexpected identifier `id', expected value

...with nothing after work 'value'. Google isn't so far very helpful. It fail one the first line of the .yaml file

I'm doing this on Ubuntu 18.04, for tool versions I get:

flatpak-builder --version
flatpak-builder 0.10.9

flatpak --version
Flatpak 1.0.6

Since this obivously works elsewhere maybe this is some version mismatch between .yaml file and flatpak-builder. Is my flatpak-builder actually trying to parse json file? Any ideas?

**Comment by jliljebl** [comment]
I updated flatpak-builder from PPA to 1.0.3 and now it is at least building something...

**Comment by jliljebl** [comment]
Ladspa 1.13 sdk was no lenger there needd to change:

        url: http://www.ladspa.org/download/ladspa_sdk_1.15.tgz
        sha256: 4229959b09d20c88c8c86f4aa76427843011705df22d9c28b38359fd1829fded

**Comment by jliljebl** [comment]
Ok, it failed with this:

FAILED: CMakeFiles/gmic.dir/src/gmic.cpp.o 
/run/ccache/bin/c++    -Ofast -g -Dgmic_build -Dcimg_use_vt100 -Dgmic_is_parallel -Dcimg_use_abort -Wno-error=narrowing -fno-ipa-sra -fpermissive -fopenmp -Dcimg_use_openmp -Dcimg_use_zlib -Dcimg_display=1 -Dcimg_appname=\"gmic\" -Dcimg_use_xshm -Dcimg_use_fftw3 -fPIE    -Dcimg_use_tiff -Dcimg_use_png -Dcimg_use_jpeg -std=gnu++11 -MD -MT CMakeFiles/gmic.dir/src/gmic.cpp.o -MF CMakeFiles/gmic.dir/src/gmic.cpp.o.d -o CMakeFiles/gmic.dir/src/gmic.cpp.o -c ../src/gmic.cpp
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
[3/5] Building CXX object CMakeFiles/libgmicstatic.dir/src/gmic.cpp.o
ninja: build stopped: subcommand failed.
Error: module gmic: Child process exited with code 1

Any ideas? gmic does not seem to be on Flathub. Does current recipe build on your system if the ladspa change from above is added?

**Comment by eszlari** [comment]
It compiles here. Have you killed the process by chance?

You could also add `disabled: true` (http://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html) to the gmic modules or simply comment out the whole module.

**Comment by jliljebl** [comment]
On second attempt it passed through the previous problem spot and is now compiling avfilter, lets see...

**Comment by jliljebl** [comment]
* Flatpak with MLT 6.6 is BAD

I had an idea what could be the issue but if 6.6.0 ain't working I really don't know what the problem is.

 I'll try tomorrow with earlier runtime to see if changing runtime helps.

**Pull request closed without merging**
